apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configmap" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.configuration }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
