{{- if not .Values.statefulSet.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    release/time: {{ date "2006-01-02T15:04:05Z07:00" now }}
    release/revision: {{ .Release.Revision | quote }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        {{- include "podTemplate" . | nindent 8 }}
{{- end }}
