# CronJob schedule https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax
# Defaults to once every Monday on 07:00 AM (once per week)
schedule: "0 5 * * 1"

successfulJobsHistoryLimit: 4
failedJobsHistoryLimit: 1

# Resources for containers started by CronJob
resources:
  requests:
    cpu: 123m
    memory: 321Mi
  limits:
    cpu: 123m
    memory: 321Mi
