apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helm-charts
  title: helm-charts
  description: "Helm charts maintained and used by the MMS Technology team."
  annotations:
    github.com/project-slug: MediaMarktSaturn/helm-charts # https://backstage.io/docs/features/software-catalog/well-known-annotations/#githubcomproject-slug
    github.com/team-slug: MediaMarktSaturn/gitops-crew # https://backstage.io/docs/features/software-catalog/well-known-annotations/#githubcomteam-slug
    mms.tech/ref_uuid: 74e193b6-9733-4ba1-89b5-6f36ac7027fe # LeanIX refUUID
    mms.tech/product_id: '0000' # Deprecated: retained temporarily for backward compatibility with legacy tooling; remove once all consumers are migrated.
    mms.tech/app_id: # # Deprecated: retained temporarily for backward compatibility with legacy tooling; remove once all consumers are migrated.
spec:
  type: library
  lifecycle: production
  owner: MediaMarktSaturn/gitops-crew
