---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
  name: {{ $.Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
