image:
  # Docker image used in container, defaults to https://explore.ggcr.dev/?repo=registry.k8s.io%2Fkubectl
  # A different image can be used as long as it contains the "kubectl" tool
  repository: registry.k8s.io/kubectl
  # Tag can be set to any Kubernetes version, to avoid unexpected compability issues it is recommended to use the same version configured for the K8s cluster
  tag: "v1.34.1"

# CronJob schedule https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax
# Defaults to once every Monday on 07:00 AM (once per week)
schedule: "0 7 * * 1"

# How much completed jobs to keep in each state
successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 3

# https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
# Defaults to 86400 seconds = 1d
ttlSecondsAfterFinished: 86400

# Resources for containers started by CronJob
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

# --field-selector value to identify pods to be cleaned up
podFieldSelector: status.phase=Failed
