---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apiserverName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apiserverLabels" . | nindent 4 }}
  annotations:
    release/time: {{ date "2006-01-02T15:04:05Z07:00" now }}
    release/revision: {{ .Release.Revision | quote }}
