installCRDs: false

# controllers
helmController:
  create: false
imageAutomationController:
  create: true
imageReflectionController:
  create: true
kustomizeController:
  create: false
notificationController:
  create: false
sourceController:
  create: false
sourceWatcher:
  create: false
watchAllNamespaces: true
