---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiserverName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apiserverLabels" . | nindent 4 }}
  annotations:
    release/time: {{ date "2006-01-02T15:04:05Z07:00" now }}
    release/revision: {{ .Release.Revision | quote }}
    {{- range $k, $v := .Values.apiserver.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: 80
      targetPort: api
  selector:
    {{- include "apiserverSelectorLabels" . | nindent 4 }}
