---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontendName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontendLabels" . | nindent 4 }}
  annotations:
    release/time: {{ date "2006-01-02T15:04:05Z07:00" now }}
    release/revision: {{ .Release.Revision | quote }}
    {{- range $k, $v := .Values.frontend.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: http
  selector:
    {{- include "frontendSelectorLabels" . | nindent 4 }}
