{{- if .Values.istio.enabled }}
{{- if .Values.istio.ingress.enabled }}
{{- if not .Values.canary.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.istio.ingress.host | quote }}
  gateways:
    - {{ .Values.istio.ingress.gateway }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}
          {{- if not (eq .Values.istio.ingress.uriPrefix "/") }}
      match:
        - uri:
            prefix: {{ .Values.istio.ingress.uriPrefix }}
      rewrite:
        uri: {{ or .Values.istio.ingress.uriRewrite "/" }}
          {{ end }}
      timeout: {{ .Values.service.timeout }}
{{- end }}
{{- end }}
{{- end }}
