{{- range .Values.serviceAccount.rbac }}
{{- if or (eq .kind "RoleBinding") (eq .kind "ClusterRoleBinding") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .kind }}
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .roleType }}
  name: {{ .roleName }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
