{{- if or .Values.encryptedSecret.data .Values.encryptedSecret.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
{{- if .Values.encryptedSecret.data }}
data:
  {{- range $k, $v := .Values.encryptedSecret.data }}
  {{ $k }}: |-
    {{ $v | indent 6 }}
  {{- end }}
{{- end }}
{{- if .Values.encryptedSecret.stringData }}
stringData:
  {{- range $k, $v := .Values.encryptedSecret.stringData }}
  {{ $k }}: |-
    {{ $v | indent 6 }}
  {{- end }}
{{- end }}

{{- end }}
