{{- if .Values.monitoring.podMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  jobLabel: {{ .Release.Name }}
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          {{- if .Values.canary.enabled }}
          - "{{- printf "%s-primary" .Release.Name -}}"
          - "{{- printf "%s-canary" .Release.Name -}}"
          {{ else }}
          - "{{ .Release.Name }}"
          {{ end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: {{ .Values.monitoring.metricsPortName | quote }}
      path: {{ .Values.monitoring.metricsPath | quote }}
      interval: {{ .Values.monitoring.scrapeInterval | quote }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout | quote }}
      followRedirects: {{ .Values.monitoring.followRedirects }}
{{ end }}
