---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: name-me-butterfly
  namespace: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
  namespace: test
data:
  my-key: my-value
  great-key: awesome-value
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: test
stringData:
  secret-key: secret-value
  great-secret: "don't tell anyone"
