statefulSet:
  enabled: true

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi

volumeMounts:
  - name: share
    mountPath: /share

sidecars:
  - name: sidekick
    image:
      repository: quay.io/heubeck/examiner
      tag: 1.14.4
    env:
      ECHO_VALUE: yehaaa
      QUARKUS_HTTP_PORT: 9090
    startupProbe:
      enabled: true
      path: /.well-known/live
      port: 9090
    livenessProbe:
      path: /.well-known/live
      port: 9090
    readinessProbe:
      path: /.well-known/ready
      port: 9090
    securityContext:
      runAsUser: 65532
      allowPrivilegeEscalation: false
    volumeMountNames:
      - share
  - name: kickback
    image:
      repository: quay.io/heubeck/examiner
      tag: 1.14.4
    env:
      ECHO_VALUE: wohooo
      QUARKUS_HTTP_PORT: 7070
    startupProbe:
      enabled: true
      path: /.well-known/live
      port: 7070
    livenessProbe:
      path: /.well-known/live
      port: 7070
    readinessProbe:
      path: /.well-known/ready
      port: 7070
    securityContext:
      runAsUser: 65532
      allowPrivilegeEscalation: false

sidecarDefaults:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
