resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi

gatewayApi:
  enabled: true
  pathPrefix: /examine
  gatewayRef:
    name: http-gateway
    namespace: default

canary:
  enabled: true
