serviceAccount:
  rbac:
    - kind: RoleBinding
      roleType: Role
      roleName: admin
    - kind: ClusterRoleBinding
      roleType: ClusterRole
      roleName: edit
    - kind: ClusterRoleBinding
      roleType: ClusterRole
      roleName: view
