resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi

sidecars:
  - name: sidekick
    image:
      repository: quay.io/heubeck/examiner
      tag: 1.11.23
    env:
      ECHO_VALUE: yehaaa
      QUARKUS_HTTP_PORT: 9090
    livenessProbe:
      path: /.well-known/live
      port: 9090
    readinessProbe:
      path: /.well-known/ready
      port: 9090
    securityContext:
      runAsUser: 65532

sidecarDefaults:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
