resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi

istio:
  enabled: true

prepJob:
  enabled: true
  image: busybox:stable
  command: ["echo", "I'm first"]
  sidecarInjection: true
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
