resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi
container:
  port: 8000
service:
  port: 8000
  backendConfig:
    enabled: true
    securityPolicyName: uri-path-policy
configuration:
  HTTP_PORT: 8000
additionalPorts:
  - name: https
    protocol: TCP
    containerPort: 8081
    servicePort: 81
  - name: grpc
    protocol: TCP
    containerPort: 8082
