apiserver:
  resources:
    requests:
      cpu: "100m"
      memory: 1024Mi
  storage:
    class: "standard"
    size: "10Mi"
  metrics:
    enabled: true
    grafana:
      dashboard: true
    serviceMonitor:
      enabled: true

frontend:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
  configEnvFrom: []
  secretEnvFrom: []
  configuration: {}
  service:
    annotations: {}
    type: ClusterIP

ingress:
  enabled: false
