---
name: Publish helm charts
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish helm charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          linting: off
          charts_dir: charts
