---
name: Release charts
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Publish charts
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate docs
        run: .github/workflows/scripts/helm-docs.sh

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Generated Chart Docs
          author: github_actions <noreply@github.com>
          delete-branch: true
          branch: generate-chart-docs/patch
          add-paths: |
            *.md
